# Generated by Django 4.2.6 on 2023-10-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('ra_aluno', models.IntegerField(help_text='Digite seu RA', primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(help_text='Digite seu Nome', max_length=45)),
                ('nome_curso', models.CharField(help_text='Escolha seu curso', max_length=30)),
                ('senha', models.CharField(help_text='Digite uma senha', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nome_curso', models.CharField(help_text='Digite o nome do curso', max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('cod_disciplina', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome_disciplina', models.CharField(max_length=30)),
                ('carga_horaria', models.CharField(max_length=3)),
                ('obrigatoria', models.BooleanField()),
                ('periodo', models.DecimalField(decimal_places=0, max_digits=1)),
                ('extensionista', models.BooleanField()),
            ],
            options={
                'ordering': ['cod_disciplina', 'nome_disciplina'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('setor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome_setor', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['setor', 'nome_setor'],
            },
        ),
        migrations.CreateModel(
            name='TrilhasOptativas',
            fields=[
                ('cod_optativa', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nome_conjunto', models.CharField(max_length=30)),
                ('ch_obrigatoria', models.DecimalField(decimal_places=0, max_digits=3)),
                ('ch_cursada', models.DecimalField(decimal_places=0, max_digits=3)),
                ('ch_faltando', models.DecimalField(decimal_places=0, max_digits=3)),
                ('ch_validada', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'ordering': ['cod_optativa', 'nome_conjunto'],
            },
        ),
        migrations.CreateModel(
            name='ReqConclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_total', models.SmallIntegerField()),
                ('ch_optativas', models.SmallIntegerField()),
                ('ch_estagio', models.SmallIntegerField()),
                ('nome_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus_app.curso')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinasCursadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_app.disciplina')),
                ('ra_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_app.aluno')),
            ],
            options={
                'ordering': ['ra_aluno', 'cod_disciplina'],
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='cod_optativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus_app.trilhasoptativas'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus_app.setor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus_app.setor'),
        ),
    ]
