# Generated by Django 4.2.7 on 2023-11-17 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoDisciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_optativa', models.CharField(max_length=4)),
                ('nome_conjunto', models.CharField(max_length=45)),
                ('ch_obrigatoria', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
            options={
                'ordering': ['cod_optativa', 'nome_conjunto'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(help_text='Digite o nome do curso', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=10, unique=True)),
                ('nome_departamento', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['departamento', 'nome_departamento'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_disciplina', models.CharField(max_length=10)),
                ('nome_disciplina', models.CharField(max_length=70)),
                ('carga_horaria', models.CharField(max_length=3)),
                ('obrigatoria', models.BooleanField()),
                ('periodo', models.DecimalField(decimal_places=0, max_digits=1)),
                ('extensionista', models.BooleanField()),
                ('Departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus_app.departamento')),
                ('cod_optativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus_app.conjuntodisciplinas')),
            ],
            options={
                'ordering': ['cod_disciplina', 'nome_disciplina'],
            },
        ),
        migrations.CreateModel(
            name='ReqConclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_total', models.SmallIntegerField()),
                ('ch_obrigatorias', models.SmallIntegerField()),
                ('ch_optativas', models.SmallIntegerField()),
                ('ch_estagio', models.SmallIntegerField()),
                ('nome_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus_app.curso')),
            ],
            options={
                'ordering': ['nome_curso', 'ch_total', 'ch_obrigatorias', 'ch_optativas', 'ch_estagio'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinasCursadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus_app.disciplina')),
                ('ra_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ['ra_aluno', 'cod_disciplina'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus_app.departamento'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.IntegerField(help_text='Digite seu RA', unique=True)),
                ('nome_aluno', models.CharField(help_text='Digite seu Nome', max_length=60)),
                ('senha', models.CharField(help_text='Digite uma senha', max_length=64)),
                ('nome_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus_app.curso')),
            ],
            options={
                'ordering': ['ra_aluno', 'nome_aluno'],
            },
        ),
    ]
