# Generated by Django 4.2.6 on 2025-06-11 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syllabus_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='senha',
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conjuntodisciplinas',
            name='ch_obrigatoria',
            field=models.DecimalField(decimal_places=0, help_text='Digite o nome do curso', max_digits=4),
        ),
        migrations.AlterField(
            model_name='conjuntodisciplinas',
            name='cod_optativa',
            field=models.CharField(help_text='Digite o nome do curso', max_length=4),
        ),
        migrations.AlterField(
            model_name='conjuntodisciplinas',
            name='nome_conjunto',
            field=models.CharField(help_text='Digite o nome do curso', max_length=45),
        ),
        migrations.AlterField(
            model_name='curso',
            name='departamento',
            field=models.ForeignKey(help_text='Selecione o Departamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus_app.departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='departamento',
            field=models.CharField(help_text='Digite a sigla do Departamento', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome_departamento',
            field=models.CharField(help_text='Digite o nome do Departamento', max_length=45),
        ),
    ]
