# Generated by Django 4.2.6 on 2025-06-16 01:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syllabus_app', '0002_remove_aluno_senha_aluno_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disciplinascursadas',
            unique_together={('ra_aluno', 'cod_disciplina')},
        ),
    ]
