# Generated by Django 4.2.6 on 2023-10-24 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_app', '0002_departamento_remove_curso_setor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome_aluno',
            field=models.CharField(help_text='Digite seu Nome', max_length=60),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus_app.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome_curso',
            field=models.CharField(help_text='Digite o nome do curso', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trilhasoptativas',
            name='nome_conjunto',
            field=models.CharField(max_length=45),
        ),
    ]
