# Generated by Django 4.2.6 on 2025-06-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_app', '0003_alter_disciplinascursadas_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reqconclusao',
            options={'ordering': ['nome_curso', 'ch_total', 'ch_obrigatorias', 'ch_optativas', 'ch_estagio', 'ch_extensionista']},
        ),
        migrations.AddField(
            model_name='reqconclusao',
            name='ch_extensionista',
            field=models.SmallIntegerField(default=0, help_text='Carga horária mínima de atividades extensionistas'),
        ),
    ]
