# Generated by Django 4.2.6 on 2023-10-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_app', '0003_alter_aluno_nome_aluno_alter_aluno_nome_curso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['ra_aluno', 'nome_aluno']},
        ),
    ]
