# Generated by Django 4.2.6 on 2025-06-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_app', '0004_alter_reqconclusao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqconclusao',
            name='ch_extensionista',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Carga horária mínima de atividades extensionistas'),
        ),
    ]
