# Generated by Django 4.2.6 on 2023-10-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_app', '0005_remove_trilhasoptativas_ch_cursada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilhasoptativas',
            name='ch_obrigatoria',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
