# Generated by Django 4.2.6 on 2025-06-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_app', '0005_alter_reqconclusao_ch_extensionista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nome_departamento',
            field=models.CharField(help_text='Digite o nome do Departamento', max_length=55),
        ),
    ]
