# Generated by Django 4.2.6 on 2025-06-20 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_app', '0006_alter_departamento_nome_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(blank=True, help_text='Selecione o curso ao qual esta disciplina pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus_app.curso'),
        ),
    ]
