# Generated by Django 4.2.6 on 2023-10-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_app', '0006_alter_trilhasoptativas_ch_obrigatoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrilhasOptativas',
            new_name='ConjuntoDisciplinas',
        ),
    ]
