# Generated by Django 4.2.6 on 2025-06-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_app', '0007_disciplina_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjuntodisciplinas',
            name='limitar_carga_horaria',
            field=models.BooleanField(default=False, help_text='Se marcado, a carga horária deste conjunto será limitada ao valor acima no cômputo geral de horas optativas.', verbose_name='Limitar Carga Horária'),
        ),
        migrations.AlterField(
            model_name='conjuntodisciplinas',
            name='ch_obrigatoria',
            field=models.DecimalField(decimal_places=0, help_text='Carga horária obrigatória ou máxima para este conjunto.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='conjuntodisciplinas',
            name='cod_optativa',
            field=models.CharField(help_text='Código do conjunto de disciplinas (Ex: 0001)', max_length=4),
        ),
        migrations.AlterField(
            model_name='conjuntodisciplinas',
            name='nome_conjunto',
            field=models.CharField(help_text='Nome do conjunto (Ex: Ciclo de Humanidades)', max_length=45),
        ),
    ]
