# Generated by Django 4.2.6 on 2023-10-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_app', '0008_alter_disciplina_nome_disciplina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reqconclusao',
            options={'ordering': ['nome_curso', 'ch_total', 'ch_optativas', 'ch_estagio']},
        ),
    ]
